### ISSUE TITLE
[Font Problem] Can't find a red heart ❤️

### ISSUE THREAD

**Issue by phfn** [fdw/rofimoji#102]
I'm trying to send a red heart(❤️) to my girlfriend. But i only found many others form of hearts. I took a look at wikipedia and it (the german one) said, the red heart is just a variant of HEAVY BLACK HEART ❤. Is there a way to get these variants?

**Comment by fdw** [comment]
You should have a red heart (also blue, green and some other colors). At least, it's in the `emojis.csv` file: `❤ red heart <small>(heart)</small>`

However, the red heart might be rendered incorrectly because of font issues. Is that maybe the case for you, too?

**Comment by phfn** [comment]
I have the "red heart" entry. But it inserts ❤ not ❤️ ...
The font isn't perfect either, but when i paste the red heart above in Signal-Desktop i get a red Heart, with rofimoji its still black...

**Comment by phfn** [comment]
Ok my Girlfried Actually recieves red hearts, so it might actually be a font issue '^^
And now i see that what in my textfield was just a black heart is now rendered red.. I think its definetly a font issue

**Comment by phfn** [comment]
![screenshot rofimoji](https://user-images.githubusercontent.com/42222671/139746037-b7bf0301-7b62-44c0-91f1-ca9f5b9c231a.png)
I installed [noto-fonts-emoji](https://archlinux.org/packages/extra/any/noto-fonts-emoji/) i think the emojis on the screenshot are partly from there and partly from somewhere (?) else.

![How the black heart looks](https://user-images.githubusercontent.com/42222671/139746476-d215d42d-9bfb-49e0-8273-ef5d6cacac97.png)

rofimoji has version 5.3.0
pango has version 1.48.10

Im on Manjaro xfce.

Maybe you have an idear..

**Comment by fdw** [comment]
To be honest, I have the same problem. After some more digging into font resolution, I don't think there is a good solution here...

The problem seems to be that your (and my) monospace font has glyphs for some emojis, like the red heart. Since it is the primary font used, its glyphs will be preferred - even if they look bad.
On the other hand, the font doesn't contain most other emojis, so for those, the system falls back to another font that implements those.
But there doesn't seem to be a way to prefer single characters from other fonts. Maybe one could remove them from the monospace font manually, but that's also some effort...
I also found one mention that always preferring the emoji font and falling back to monospace would not be a good idea, as noto emoji also implements numbers, for example :/

If you have any other ideas, please share :)

**Comment by fdw** [comment]
As there have been no updates, I'll close this ticket. Please re-open if you have more comments or questions 🙂
