### ISSUE TITLE
Use frecency in search

### ISSUE THREAD

**Issue by emiham** [fdw/rofimoji#110]
Quite often I open Rofimoji, see the emoji I want as one of my most frequent ones, but then I have to type out the whole name anyway since that's usually faster than using the arrow keys and visually confirming the right emoji is highlighted. It would be great if frecency still applied when you start searching.

**Comment by fdw** [comment]
It took my some reasoning, as there are two problems to be solved: First - like you said - more frecently entries should be easier to choose, as they're more often used for a reason.
On the other hand, I added sorting specifically to prefer better matches over worse ones (see #59). However, it's not possible to have both at the same time.

I think that one can assume that frecent entries are preferred in the vast majority of time. Choosing something completely new is something people don't do often, so it's okay to worsen that use-case in order to improve the more frequent one.

But: I'm not dead set on this. If there are other possibilities, or things I've missed, please chime in 🙂

**Comment by emiham** [comment]
Hmm, yes, I see the problem now. I was hoping a combination would be possible, but I guess nothing is as simple as you think when you open an issue!

> I think that one can assume that frecent entries are preferred in the vast majority of time. Choosing something completely new is something people don't do often, so it's okay to worsen that use-case in order to improve the more frequent one.

I agree with this. Another argument for this is that it's a bit confusing for users to see the entry they want, and then have it disappear as soon as they start searching. I think having a consistent sorting mechanism when you go from no input to first input is good, whether that is by frecency or another ordering. 

I'll leave this issue open if you want to let others chime in for a bit, but feel free to close it whenever as the latest commit works great.
