### ISSUE TITLE
system freeze when using action clipboard

### ISSUE THREAD

**Issue by Nachtpfoetchen** [fdw/rofimoji#112]
Rofi version: 1.7.2
Rofimoji version: 5.3.0

When i try to use option -a clipboard when i select an emoji i can not exit rofi anymore and interact with my system at all. a restart helps but it freezes when i try it again. mew.

**Comment by fdw** [comment]
Okay, some questions: How do you start `rofimoji`? Are you on X or Wayland? Which tool do you use to work with the clipboard?

**Comment by Nachtpfoetchen** [comment]
i start rofimoji using rofi
my rofi config:
```
configuration {
	modi: "drun,window,ssh,emoji:rofimoji -a copy";

}
@theme "purple"
```

and i launch rofi using i3 config:
`
bindsym $mod+d exec "rofi -show drun"`
i tried to use it with firefox.

**Comment by fdw** [comment]
Do you have `xsel` or `xclip` installed?

**Comment by Nachtpfoetchen** [comment]
yes xclip is installed:

`1 extra/xclip 0.13-3 (15.0 KiB 34.4 KiB) (Installed)`

**Comment by fdw** [comment]
I think I know the problem... can you please try `-a copy` instead?

**Comment by Nachtpfoetchen** [comment]
`-a copy` works

**Comment by fdw** [comment]
I think the problem (or part of the problem) is that `clipboard` wants to insert the character right away. But since you're using the rofi mode, it tries to insert the character into `rofi`, not into the application in the background! Something in that process screws up rofi, too.

Unfortunately, there's not much we can do - either you use `copy` in the mode, or you use `rofimoji` standalone. Sorry 😕
