### ISSUE TITLE
--max-recent not having an effect

### ISSUE THREAD

**Issue by polyzen** [fdw/rofimoji#183]
Noticed this as I had been using `max-recent = 0` in my config. In my case I can/should just switch to `no-frecency.`

Edit: rofimoji 6.3.0

**Comment by fdw** [comment]
So, you still see the bar of recently used characters, even though you set `max-recent` to `0`? Are you using the `rofi` mode or the standalone version?

**Comment by polyzen** [comment]
Oh I forgot there was a bar. I don't see the bar, but (presumably) all the frecency items listed at the top of everything else. Haven't yet tested without using neither options.

**Comment by fdw** [comment]
Okay, you not seeing the bar is good, that means `--max-recent=0` is working 🙂

The sorting by frecency is independent of that and can be configured with `--no-frecency`. Does that work for you?

**Comment by toxision** [comment]
Maybe this is related....
Since 6.3.0 the history bugs. Every time I select an item, it's searchable text disappears and thus, another search will not bring up that emoji anymore.
![Screenshot_2024-05-02_21-43-25](https://github.com/fdw/rofimoji/assets/71572691/c160ce19-6c96-44ff-8e95-37768f42a841)

If this is unrelated, I will open a new issue

Best regards,
Chris

**Comment by fdw** [comment]
Yes, this looks like a different problem; can you please open a new issue please?

Also, which files have you configured?

**Comment by polyzen** [comment]
Sorry forgot recent and frecency were different 😅
