### ISSUE TITLE
[Request] Remove the "-i" flag from dmenu

### ISSUE THREAD

**Issue by junnunkarim** [fdw/rofimoji#191]
Since the `-i` flag is hardcoded to your [dmenu class](https://github.com/fdw/rofimoji/blob/a5b934a19d65fdba61ad8dbf831d81e84cc46097/src/picker/selector/dmenu.py#L28C9-L28C69), rofimoji dosn't open with [case-insensitive](https://tools.suckless.org/dmenu/patches/case-insensitive/) patch applied to dmenu.

Since it is possible to provide argments for dmenu through `--selector-args`, the `-i` can be added if needed.
So could you consider removing the `-i` flag?

**Comment by fdw** [comment]
I'm hesitant to remove the `-i`, because that would degrade the experience for everyone who uses `dmenu` without the patch. I don't think `rofimoji` works well when case-sensitive, and forcing people to add `selector-args` to make it usable feels wrong.

The ideal solution, in my eyes, would be to change the patch to still accept `-i`, but not doing anything there. Because right now, you have something that is mostly indistinguishable from the normal `dmenu`, but is also incompatible with it. Or is there some way to automatically check whether the flag is supported?

**Comment by junnunkarim** [comment]
Yes, I do understand your point.
How about first running it with `-i` and  checking the `stderr` of `subprocess.run`?
If it is not empty then run it again without  `-i` a second time?

**Comment by junnunkarim** [comment]
I have come to the conclusion that there is actually no need to remove the `-i` flag. Thus I have now removed the case-insensitive patch from my dmenu build.
So I am closing this issue.
