### ISSUE TITLE
Add support for wofi's column options, and make `--hidden-descriptions` work with wofi

### ISSUE THREAD

**Issue by MoutonDemocrate** [fdw/rofimoji#208]
Currently, setting the wofi argument `-w` doesn't do anything.

![My wofi, using my css and an empty config file](https://github.com/user-attachments/assets/bd99e6da-99a7-473a-a3d5-d050f8c0043f)
called with `wofi -s ~/.config/wofi/mouton.css --show drun -I -i -w 5 --normal-window -p "$(fortune -s -n 100 | sed ':a;N;$!ba;s/\n[[:space:]]\{2\}--/ --/')"`

![My rofimoji, using the same css](https://github.com/user-attachments/assets/cfcf27fa-c2a4-4472-af00-4e96aa5d3728)
called with `rofimoji --action copy type --use-icons -r "Search for an emoji..." --hidden-descriptions --selector-args="-w 5 -s ~/.config/wofi/mouton.css --normal-window"`

You can see that the columns aren't present, and that the descriptions are still there. Or is it a problem with my wofi ? So far I haven't found any issue with wofi directly, I apologise if this issue is misdirected.

Thanks much in advance, and thanks a lot for the software ! Really useful and pretty flexible.

**Comment by fdw** [comment]
That's several problems, let's unpack them:

1. `--use-icons`: This is just not supported by `wofi`, unfortunately. `rofi`'s icon support allows Unicode characters, but `wofi` wants an image file.
2. `--hidden-descriptions`: This, too, is not really supported by `wofi`. `rofi` has the nice feature of having searchable, but invisible descriptions, so you can still search for a character. `wofi` doesn't have that, as far as I can see, so you couldn't search anymore. I don't think this would be useful.
3. `--selector-args="-w 5": `wofi` seems to have the "feature" where `--columns` is only a suggestion, but the length of each entry will also have an impact. Since each entry from `rofimoji` has a longer text, five columns (or even two) doesn't work.

If `rofimoji` would hide the text descriptions and show only the icon, `-w` would also work, but then you couldn't search for any character - only navigate with the arrow keys to choose them. Personally, I don't think this is very helpful, but what do you think?

**Comment by MoutonDemocrate** [comment]
Welp, that's just how it is when working in tandem with another software. This isn't anything too important, so it's fine, rofimoji is already pretty damn useful without the features at stakes here.

Thanks for your answer ! Have a nice day :)

**Comment by fdw** [comment]
Thank you for the kind words 😊

Maybe you could open feature requests over at `wofi`? Or I can add support for `--hidden-descriptions`, even if that breaks searching, if you think that's useful.

**Comment by fdw** [comment]
I think this is done, so I'm closing this issue. If you - or anyone else - sees a use case for not having any searchable descriptions, please open this issue again 🙂
