### ISSUE TITLE
[feat request] Allow user to specify X-clipboard tool

### ISSUE THREAD

**Issue by ginglis13** [fdw/rofimoji#21]
I already have `xclip` installed and use it as my primary x-clipboard tool. This project lists `xsel` as a dependency, and I see that in `rofimoji.py`, `xsel` is run through a `Popen` call. I think it would be nice if the user could specify their preferred x selection tool in running rofimoji, to eliminate the strict dependency on `xsel`.

**Comment by fdw** [comment]
I'm a bit torn on this issue. I can easily your point and I'd like to support this - why install another tool if you have a similar one already?

On the other hand, after trying to implement it, the code becomes a lot more complex, as it tries to handle both variants. Another solution would be to use [Pyperclip](https://github.com/asweigart/pyperclip), but then rofimoji would have dependencies, which is something I wanted to avoid in order to have a small and simple tool.

Ideas? Is it acceptable to have dependencies (even though it makes the installation more difficult)?

**Comment by andaag** [comment]
All this does is wrap xsel/xdotool, if it used native functions it might be more useful than wrapping commands. I recon most people who install this is ok with installing xsel, its a microscopic dependency.

I'd prefer going for python-xlib instead, native and should be faster performance wise, probably more reliable than running bash commands. And if its a wish to keep it to a single executable building an egg/one of the other bundle methods.

**Comment by fdw** [comment]
Thanks for the hint with python-xlib, @andaag. I've had a longer look at it and remain undecided: It would solve the problem between xsel and xlip, but it works on a very low level that feels too low for rofimoji. I don't want to have to deal with the X protocol, to be honest, and I think this would rather invite more bugs in.

If anyone wants to have a go at it, feel free to open a PR 🙂

**Comment by fdw** [comment]
Some more thought on this: As Wayland is becoming a thing now, I'd rather not depend on X. If someone knows of a nice abstraction for both, I'd welcome it (or a PR 😉)!

**Comment by markstos** [comment]
To replace `xdotool type` there is `wtype`: https://github.com/atx/wtype

**Comment by markstos** [comment]
One way to solve this is to move the commands to `xsel` and `xdotool` to a config file or command line arguments. Leave `xsel` and `xdotool` as the defaults, so the change is backwards compatible. Then people can specify `wtype` and `wl-clipboard` if there are running under Wayland without XWayland.

**Comment by fdw** [comment]
Thanks for the links, @markstos !

It looks like a larger problem, though, as the usage (parameters etc) differs between them. We'd need another abstraction layer there, and I'm not too keen on writing it 😉

**Comment by fdw** [comment]
I don't want to merge this branch without some more testing. So, if you are interested in this feature, please give it a whirl and report back!

**Comment by JustinLovinger** [comment]
@fdw I have been using this branch with Sway for several days now. I ran into an issue where my keyboard became unresponsive after inserting directly with `wtype`. However, I assume that is an issue with wtype or Sway, not rofimoji. My Sway is a little old so I was waiting to upgrade before reporting anything. Copying to clipboard works fine.

**Comment by markstos** [comment]
I tested this branch on Wayland, testing with Alacritty as the active app, a native Wayland app. Here's what I found:
  
 * ✅ Typing worked
 * ☠️  `-p` did not copy to clipboard
 * 🔥 `-c` did not copy  to clipboard

I have `wl-copy` installed. `WAYLAND_DISPLAY` is set in my environment. 

Attempting type "Woman with light skin with red hair" typed three emojis: One for woman, one for red hair and one for skin tone. I presume that relates to Alacritty's emoji support.  Let's try typing "woman with light skin and red hair" into this text box:‍聆  Hmm, I'm not sure what is, but it doesn't look right either.

I'll try just pasting the emoji: 👩🏻‍🦰 That works. 

I compared how this works to `rofi-emoji` and I prefer this one. The UI is cleaner, and I like the default skin tone support as well as the support for typing and remembering recent emojis.

**Comment by markstos** [comment]
When detecting the Wayland environment, the code assumes that if `WAYLAND_DISPLAY` is present, then `wl-copy` is also present. The code should check that both are true.

**Comment by fdw** [comment]
> -p did not copy to clipboard
> -c did not copy to clipboard

That sound like the integration of `wl-copy` doesn't work. I don't think the `supported` method is wrong, since it works in the `Typer`. Unfortunately, I don't have Wayland running anywhere, so I can't really test it. If you can, could you please check whether something like `echo 🐧 | wl-copy` works? Maybe we need to set `-t text/plain` as well...

> One for woman, one for red hair and one for skin tone. I presume that relates to Alacritty's emoji support.
Yes, I would believe that is Alacritty, unfortunately.

>  Let's try typing "woman with light skin and red hair" into this text box:‍聆 Hmm, I'm not sure what is, but it doesn't look right either.
Which browser are you using? Firefox doesn't allow me to type any emojis at all 😟

> I compared how this works to rofi-emoji and I prefer this one. The UI is cleaner, and I like the default skin tone support as well as the support for typing and remembering recent emojis.
Thank you very much, that is very kind 🙏

> When detecting the Wayland environment, the code assumes that if WAYLAND_DISPLAY is present, then wl-copy is also present. The code should check that both are true.
I'm not too sure - what should `rofimoji` do if the env variable is set, but `wl-copy` isn't there? Is there some other tool besides `wl-copy` that is used on Wayland?

**Comment by JustinLovinger** [comment]
@fdw to the best of my knowledge, `wl-copy` (which is part of `wl-clipboard`) is the de-facto command line copy tool for Wayland. Also, I'm using rofimoji with NixOS 20.03, Sway, and Alacritty, `-c` and `-p` function for me. My `wl-clipboard` is version 2.0 . I even double-checked with the latest rofimoji.

**Comment by markstos** [comment]
Yes, my PR fixes copy/paste for me. @JustinLovinger correctly guessed why it had failed for me and not him. I had xclip installed (because I also have X11 installed), and the clipboard-tool detection order was picking `xclip` before it checked to see if I was running under Wayland.

I was using `Qutebrowser` for my browser, which is a Chromium-based browser. 

If `WAYLAND_DISPLAY` is set but `wl-copy` is not found,  I think copying is just not going to work. Ideally, an error would be returned to the user suggesting that they install `wl-copy` is they want that feature to work. 

The behavior should be the same has having neither `xclip` nor `xsel` installed.

**Comment by fdw** [comment]
Thanks for all your comments and the PR! I have some ideas how to improve the functionality, but I think the fundamental work is done already, and all that's left is some polishing.

Regarding your `Qutebrowser` issue, @markstos: If you want to, please feel free to open a separate issue so it doesn't get lost here.

**Comment by fdw** [comment]
I've written some more code that should make this whole feature easier to maintain and use. Please check out the latest commit on the feature branch and test it. If it works, this is going to be the next version of `rofimoji` 🙂

**Comment by JustinLovinger** [comment]
> I've written some more code that should make this whole feature easier to maintain and use. Please check out the latest commit on the feature branch and test it. If it works, this is going to be the next version of `rofimoji`

Latest commit works for me 👍

**Comment by fdw** [comment]
Thank you. It's now merged to main!
