### ISSUE TITLE
Use as a modi

### ISSUE THREAD

**Issue by farzadmf** [fdw/rofimoji#24]
Hi,

First of all, thank you for the interesting work you've done on this project. I was just wondering if this script has to be executed stand-alone, or is it possible to integrate it into the "normal" rofi I use, and maybe switch to this `modi` using `Ctrl-Tab`

Thank you

**Comment by fdw** [comment]
Hi,

I've thought about this as well, but it seems difficult to achieve the nested dialog for color, for example.
At least for now, I'm not actively working on it. So if you want, play with it and open a PR 😉

**Comment by farzadmf** [comment]
Cool, thank you for your reply. I'll see what I can do :). So, I'm not going to close this as something might happen for it

**Comment by fdw** [comment]
I have looked into this a bit deeper, and I still think it can be done, but only with a lot of effort.

Basically, rofi would call a script to get a list of options. After the user chose, the script gets called again with the selection as arguments. Therefore, in order to support the nested menus, `rofimoji` would have to keep track of its state in a file somewhere.

If anyone wants to implement these, I'd love to merge it! So far, however, I'm not sure whether *I* want to rewrite everything...

**Comment by fdw** [comment]
Another update: I've looked even deeper into this, but there is a big obstacle: You cannot use custom keybindings with a mode 😟
So, what could be done is to use cli parameters or a submenu where you have to choose the insertion mode. Both don't feel good, to be honest.

Does anyone have an opinion on this?

**Comment by polyzen** [comment]
I have no experience with using modi as I only have the `run` modi enabled. I gave rofimoji top priority (added `99999 rofimoji` to the top of my `.cache/rofi-3.runcache`), so all I have to do it `win+d+enter`.

**Comment by fdw** [comment]
I spent some more time on this idea, and while I'd love to have a combi mode of rofimoji with different character sets, I don't see it working without custom keybindings.

I'll close this ticket, as I won't implement it. If anyone else wants to, feel free. I'm open to PRs.
