### ISSUE TITLE
Clipboard Switch has no effect

### ISSUE THREAD

**Issue by daniel-tigges** [fdw/rofimoji#25]
When starting rofimoji with the -c or --use-clipboard switch it has no effect. Emojis are still directly inserted.

This could be easily fixed by changing the following conditions:

```
        if returncode == 0 and not args.use_clipboard:
            insert_emojis(emojis, active_window, args.use_clipboard)
        elif returncode == 10 or args.use_clipboard:
            copy_emojis_to_clipboard(emojis)
        elif returncode == 11:
            type_emojis(emojis, active_window)
        elif returncode == 12:
            copy_paste_emojis(emojis, active_window)

```

**Comment by chmduquesne** [comment]
Hi! I am not the author, but I contributed to the code so I think I can answer this one.

The intended use of `--use-clipboard` is *not* to save the emoji in the clipboard. It is to insert the emoji via first copying it, then pasting it from the clipboard. Some programs (looking at you, firefox!) do not accept inputs from xdotool via its `--type` option. This makes the clipboard the only reliable way to insert the emoji. Of course, since this clears the clipboard, rofimoji has a mechanism to save and restore the original content after the copy-paste has happened. AFAIK, the behavior you want does not exist in rofimoji.

Hope this helps!

**Comment by fdw** [comment]
@chmduquesne is almost completely right (thank you 🙂)

As you can read [in the readme](https://github.com/fdw/rofimoji#insertion-method), `--use-clipboard` does not copy the selecte emojis to the clipboard but will insert them using the clipboard. If you only want to copy them, rofimoji can do this with `Alt+c`.
There is no cli switch for this (yet). Do you think this would be useful?

**Comment by daniel-tigges** [comment]
Thanks for the clarification. In my opinion a dedicated "mode" that simply saves the emoji into the clipboard could be useful as well (at least for me) 

Thanks for your fast responses.

**Comment by charvp** [comment]
I would like a switch that saves the emoji to the keyboard as well, since xdotool doesn't work on wayland.

**Comment by chmduquesne** [comment]
We could experiment with https://github.com/ReimuNotMoe/ydotool. It's supposed to replace xdotool in the wayland universe.

**Comment by fdw** [comment]
If anyone wants to add support for Wayland, I'm all for it. I'm not running it yet, though, so I can't do it myself.

Regarding the switch, I keep that on my list, but first I want a good solution regarding modi and other files. It makes no sense to add a new switch when a rewrite is necessary 😉

**Comment by fdw** [comment]
`master` contains the switch now 🙂 There is no release yet, however.
