### ISSUE TITLE
[Feature request] Option to show Unicode character codepoint(s)

### ISSUE THREAD

**Issue by katacarbix** [fdw/rofimoji#48]
Often times I'll need to look up the specific codepoint of an emoji or other character online and it would be much easier to just have it in the menu. I'm thinking it could be dynamically inserted into the entry text, like so:

- 😀 `<small>1F600</small> grinning face <small>(face, grin, grinning face)</small>`
- 🧑‍💻 `<small>1F9D1+200D+1F4BB</small> technologist <small>(coder, developer, inventor, software, technologist)</small>`

There are some considerations for implementing this:
- Codepoints are not stored in the character files so they would need to be generated on-the-fly.
- Should it omit invisible joiners? They're important to know sometimes.
- Can it accurately insert the text in the right spot or should it be attached to an end?

**Comment by katacarbix** [comment]
It wasn't too hard to implement. Let me know how this looks and if you want me to change anything!

**Comment by fdw** [comment]
Hi @katacarbix, first off: Thank you!
You haven't even given me a chance to look at the ticket before you just implemented it yourself 😉

So, before I look deeper at the PR (on first glance it looks good, so thanks again), I'd like to ask you: What exactly is your use case? Do you just want to look at the codepoint, or do you want to type it anywhere? Or something completely different?
I'm asking because first, there might be a more comfortable way to do it, and secondly, iterating over all items might slow `rofimoji` noticably down, which I'd like to avoid.

FInally, as a side note: It might be an interesting idea to type the character into another window using the codepoint. We could have a look at that, as well. Maybe it finally fixes Firefox 😉

**Comment by katacarbix** [comment]
Of course!

Sometimes I want to find a high quality image of a character in an emoji font's repo, and to do that I need the codepoint(s). The invisible characters included in the filenames sometimes vary between fonts (such as twemoji's [`1f3c4-1f3fe-200d-2640-fe0f`](https://github.com/twitter/twemoji/blob/master/assets/svg/1f3c4-1f3fe-200d-2640-fe0f.svg), noto's [`1f3c4_1f3fe_200d_2640`](https://github.com/googlefonts/noto-emoji/blob/master/svg/emoji_u1f3c4_1f3fe_200d_2640.svg), and joypixels' [`1f3c4-1f3fe-2640`](https://github.com/joypixels/emoji-assets/blob/master/png/128/1f3c4-1f3fe-2640.png)) so I wasn't sure if they should be included or not. The separators vary too (- vs _).

I didn't notice much change in performance but they certainly don't need to be generated for every single one. I haven't really looked into keybindings but it would definitely be faster if there was a shortcut to copy/paste the codepoint for that specific character.

**Comment by katacarbix** [comment]
I added a shortcut to copy the codepoint to the clipboard, which is `alt-U` for now. If the skin tone option is set to 'ask' it works if you fire the shortcut before selecting tone.

**Comment by fdw** [comment]
I think that feature makes sense :) I'll go and have a look at your PR.
