### ISSUE TITLE
Font Awesome Icons?

### ISSUE THREAD

**Issue by rjhilgefort** [fdw/rofimoji#54]
Hello! Thanks for this awesome tool! I was thinking it would be pretty useful to integrate Font Awesome icons as a data set. Is that something someone has done? If not, how much work would it be to format them for use here? I'm assuming it just comes down to doing a [custom character file](https://github.com/fdw/rofimoji#custom-character-files), so I'll look into that unless someone has already done it.

**Comment by fdw** [comment]
Hey, thank you! :)

That's a cool idea, and I don't know of any existing implementation. All you need to do, like you said, is to create a custom character file. If you can, you should try to build it automatically, for example from an API or web page.

Ping me if you need any help with it :)

**Comment by katacarbix** [comment]
I wrote an extractor for [Nerd Fonts](https://www.nerdfonts.com/) that's in a [branch on my fork](https://github.com/katacarbix/rofimoji/tree/data/nerd-fonts) but I'm not sure if it's ready for a PR yet. Nerd Fonts include Font Awesome icons, among other icon fonts, but the actual character codes don't match. Instead of writing extractors for every possible icon font I think this makes more sense.

If you want to use the [data file](https://github.com/katacarbix/rofimoji/blob/data/nerd-fonts/picker/data/nerd_font.csv) right now you can download it and run rofimoji with `--files /path/to/nerd_font.csv`

**Comment by rjhilgefort** [comment]
Nice, it looks like that mostly works, now I just need to get nerd fonts installed to be able to see em. Thanks!

**Comment by fdw** [comment]
Please open a PR for it if you feel it's ready, @katacarbix. Thanks again 🙂

**Comment by katacarbix** [comment]
Okay, cool! I'll polish it up over the next few days.

**Comment by fdw** [comment]
Is this good enough, or do you want a separate file only for Font Awesome?
